export const projectsData = [
  {
    id: 'p1',
    name: 'Projeto Água Segura',
    institution: 'aias',
    institutionName: 'AIAS, IP',
    status: 'in-progress',
    startDate: '2023-01-15',
    endDate: '2024-06-30',
    responsible: 'Carlos Oliveira',
    progress: 65,
    budget: 3500000,
    description:
      'Implementação de sistemas de tratamento de água em áreas rurais para garantir acesso à água potável.',
  },
  {
    id: 'p2',
    name: 'Projeto de Saneamento Urbano',
    institution: 'aias',
    institutionName: 'AIAS, IP',
    status: 'in-progress',
    startDate: '2022-11-05',
    endDate: '2024-11-20',
    responsible: 'Ana Silva',
    progress: 40,
    budget: 7200000,
    description:
      'Melhoria das infraestruturas de saneamento em áreas urbanas para reduzir riscos de saúde pública.',
  },
  {
    id: 'p3',
    name: 'Projeto CERRP',
    institution: 'aias',
    institutionName: 'AIAS, IP',
    status: 'pending',
    startDate: '2024-03-01',
    endDate: '2025-09-30',
    responsible: 'Manuel Costa',
    progress: 10,
    budget: 4800000,
    description:
      'Resposta de emergência e recuperação após ciclones para restabelecer serviços essenciais.',
  },
  {
    id: 'p4',
    name: 'Projeto Água Segura',
    institution: 'dnaas',
    institutionName: 'DNAAS',
    status: 'in-progress',
    startDate: '2023-02-20',
    endDate: '2024-08-15',
    responsible: 'Luísa Mendes',
    progress: 58,
    budget: 2900000,
    description:
      'Expansão do acesso à água potável em comunidades vulneráveis.',
  },
  {
    id: 'p5',
    name: 'Projeto XXXX',
    institution: 'dnaas',
    institutionName: 'DNAAS',
    status: 'completed',
    startDate: '2022-06-10',
    endDate: '2023-12-15',
    responsible: 'João Ferreira',
    progress: 100,
    budget: 1800000,
    description:
      'Monitoramento da qualidade da água em bacias hidrográficas críticas.',
  },
  {
    id: 'p6',
    name: 'Projeto XXXXX',
    institution: 'dnaas',
    institutionName: 'DNAAS',
    status: 'delayed',
    startDate: '2023-04-01',
    endDate: '2024-04-01',
    responsible: 'Teresa Santos',
    progress: 35,
    budget: 5100000,
    description:
      'Desenvolvimento de novas tecnologias para tratamento de águas residuais.',
  },
];

export const documentsData = [
  {
    id: 'd1',
    name: 'Plano de Gestão Ambiental AIAS 2024',
    institution: 'aias',
    projectId: null,
    category: 'Gestão Ambiental',
    uploadDate: '2024-01-10',
    uploadedBy: 'Carlos Oliveira',
    type: 'pdf',
    size: '4.2 MB',
  },
  {
    id: 'd2',
    name: 'Relatório de Progresso Q1 - Água Segura',
    institution: 'aias',
    projectId: 'p1',
    category: 'Relatórios',
    uploadDate: '2024-04-05',
    uploadedBy: 'Ana Silva',
    type: 'docx',
    size: '2.8 MB',
  },
  {
    id: 'd3',
    name: 'Especificações Técnicas - Sistema de Tratamento',
    institution: 'aias',
    projectId: 'p1',
    category: 'Técnico',
    uploadDate: '2023-11-22',
    uploadedBy: 'Manuel Costa',
    type: 'pdf',
    size: '8.5 MB',
  },
  {
    id: 'd4',
    name: 'Avaliação de Impacto Social - Saneamento Urbano',
    institution: 'aias',
    projectId: 'p2',
    category: 'Impacto Social',
    uploadDate: '2023-12-15',
    uploadedBy: 'Ana Silva',
    type: 'pdf',
    size: '6.3 MB',
  },
  {
    id: 'd5',
    name: 'Plano de Gestão Ambiental DNAAS 2024',
    institution: 'dnaas',
    projectId: null,
    category: 'Gestão Ambiental',
    uploadDate: '2024-01-12',
    uploadedBy: 'Luísa Mendes',
    type: 'pdf',
    size: '3.9 MB',
  },
  {
    id: 'd6',
    name: 'Relatório Técnico - Qualidade da Água',
    institution: 'dnaas',
    projectId: 'p4',
    category: 'Técnico',
    uploadDate: '2024-03-20',
    uploadedBy: 'João Ferreira',
    type: 'pdf',
    size: '5.1 MB',
  },
  {
    id: 'd7',
    name: 'Plano de Engajamento Comunitário',
    institution: 'dnaas',
    projectId: 'p6',
    category: 'Engajamento',
    uploadDate: '2023-10-05',
    uploadedBy: 'Teresa Santos',
    type: 'docx',
    size: '1.8 MB',
  },
  {
    id: 'd8',
    name: 'Orçamento Revisado - Projeto XXXX',
    institution: 'dnaas',
    projectId: 'p5',
    category: 'Financeiro',
    uploadDate: '2023-09-18',
    uploadedBy: 'João Ferreira',
    type: 'xlsx',
    size: '1.2 MB',
  },
];

export const notificationsData = [
  {
    id: 'n1',
    title: 'Prazo se aproximando',
    message:
      'O prazo para entrega do relatório trimestral do Projeto Água Segura vence em 5 dias.',
    date: '2024-04-25T10:30:00',
    read: false,
    type: 'warning',
    project: 'p1',
  },
  {
    id: 'n2',
    title: 'Novo documento disponível',
    message:
      'Novo documento "Avaliação de Qualidade da Água" foi adicionado ao projeto CERRP.',
    date: '2024-04-24T14:15:00',
    read: false,
    type: 'info',
    project: 'p3',
  },
  {
    id: 'n3',
    title: 'Atualização de status',
    message:
      'O status do Projeto de Saneamento Urbano foi alterado para "Em andamento".',
    date: '2024-04-23T09:45:00',
    read: true,
    type: 'success',
    project: 'p2',
  },
  {
    id: 'n4',
    title: 'Reunião agendada',
    message:
      'Reunião de revisão do Projeto XXXXX agendada para 30/04/2024 às 14:00.',
    date: '2024-04-22T16:20:00',
    read: true,
    type: 'info',
    project: 'p6',
  },
  {
    id: 'n5',
    title: 'Atraso identificado',
    message:
      'O Projeto XXXXX está atrasado em relação ao cronograma previsto. Ação necessária.',
    date: '2024-04-21T11:00:00',
    read: true,
    type: 'error',
    project: 'p6',
  },
];

export const usersData = [
  {
    id: 'u0',
    name: 'Admin',
    email: 'admin@email.com',
    institution: 'aias',
    role: 'admin',
    lastActive: '2024-04-26T10:00:00',
  },
  {
    id: 'u1',
    name: 'Carlos Oliveira',
    email: 'carlos.oliveira@aias.gov.mz',
    institution: 'aias',
    role: 'admin',
    lastActive: '2024-04-25T08:30:00',
  },
  {
    id: 'u2',
    name: 'Ana Silva',
    email: 'ana.silva@aias.gov.mz',
    institution: 'aias',
    role: 'manager',
    lastActive: '2024-04-24T15:45:00',
  },
  {
    id: 'u3',
    name: 'Manuel Costa',
    email: 'manuel.costa@aias.gov.mz',
    institution: 'aias',
    role: 'user',
    lastActive: '2024-04-23T11:20:00',
  },
  {
    id: 'u4',
    name: 'Luísa Mendes',
    email: 'luisa.mendes@dnaas.gov.mz',
    institution: 'dnaas',
    role: 'admin',
    lastActive: '2024-04-25T09:15:00',
  },
  {
    id: 'u5',
    name: 'João Ferreira',
    email: 'joao.ferreira@dnaas.gov.mz',
    institution: 'dnaas',
    role: 'manager',
    lastActive: '2024-04-24T14:30:00',
  },
  {
    id: 'u6',
    name: 'Teresa Santos',
    email: 'teresa.santos@dnaas.gov.mz',
    institution: 'dnaas',
    role: 'user',
    lastActive: '2024-04-22T10:00:00',
  },
];

export const chartData = {
  projectProgress: [
    { name: 'Projeto Água Segura (AIAS)', progress: 65 },
    { name: 'Projeto de Saneamento Urbano', progress: 40 },
    { name: 'Projeto CERRP', progress: 10 },
    { name: 'Projeto Água Segura (DNAAS)', progress: 58 },
    { name: 'Projeto XXXX', progress: 100 },
    { name: 'Projeto XXXXX', progress: 35 },
  ],
  budgetUtilization: [
    { name: 'P. Água Segura (AIAS)', allocated: 3500000, used: 2275000 },
    { name: 'P. Saneamento Urbano', allocated: 7200000, used: 2880000 },
    { name: 'P. CERRP', allocated: 4800000, used: 480000 },
    { name: 'P. Água Segura (DNAAS)', allocated: 2900000, used: 1682000 },
    { name: 'P. XXXX', allocated: 1800000, used: 1800000 },
    { name: 'P. XXXXX', allocated: 5100000, used: 1785000 },
  ],
  documentsPerCategory: [
    { name: 'Gestão Ambiental', count: 2 },
    { name: 'Relatórios', count: 1 },
    { name: 'Técnico', count: 2 },
    { name: 'Impacto Social', count: 1 },
    { name: 'Engajamento', count: 1 },
    { name: 'Financeiro', count: 1 },
  ],
  projectStatus: [
    { name: 'Em Andamento', count: 3 },
    { name: 'Concluído', count: 1 },
    { name: 'Atrasado', count: 1 },
    { name: 'Pendente', count: 1 },
  ],
  monthlyProgress: [
    {
      month: 'Jan',
      'P. Água Segura (AIAS)': 40,
      'P. Saneamento Urbano': 25,
      'P. CERRP': 5,
      'P. Água Segura (DNAAS)': 35,
      'P. XXXX': 90,
      'P. XXXXX': 20,
    },
    {
      month: 'Fev',
      'P. Água Segura (AIAS)': 45,
      'P. Saneamento Urbano': 28,
      'P. CERRP': 5,
      'P. Água Segura (DNAAS)': 40,
      'P. XXXX': 93,
      'P. XXXXX': 23,
    },
    {
      month: 'Mar',
      'P. Água Segura (AIAS)': 50,
      'P. Saneamento Urbano': 30,
      'P. CERRP': 8,
      'P. Água Segura (DNAAS)': 45,
      'P. XXXX': 95,
      'P. XXXXX': 25,
    },
    {
      month: 'Abr',
      'P. Água Segura (AIAS)': 65,
      'P. Saneamento Urbano': 40,
      'P. CERRP': 10,
      'P. Água Segura (DNAAS)': 58,
      'P. XXXX': 100,
      'P. XXXXX': 35,
    },
  ],
};
